apiVersion: v1
kind: Pod
metadata:
  name: erase-una-vez-5
spec:
  containers:
  - name: server
    image: nginx:alpine
    volumeMounts:
    - name: volume
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: volume
    image:
      reference: ghcr.io/mmorejon/erase-una-vez-5:main
      pullPolicy: IfNotPresent
